{% set name = "shift-smce-user-guide" %}
{% set version = "1.0.1" %}

package:
  name: "{{ Shift SMCE User Guide|shift-smce-user-guide }}"
  version: "{{ 0.01 }}"

source:
  git_url: https://github.com/EvanDLang/shift-smce-user-guide

build:
  number: 0
  script: "$PYTHON -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - shift-smce-user-guide

about:
  home: https://shift-smce-user-guide.readthedocs.io/en/latest/
  license: GPLv3
  license_family: GPL3
  license_file: LICENSE
  summary: Documentation for SHIFT SMCE

extra:
  recipe-maintainers:
    - EvanDLang
